spring:
  application:
    name: mspets

  datasource:
#    url: jdbc:mysql://localhost:3306/db_pets?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSL=false
    url: jdbc:mysql://mysql:3306/db_pets?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Brazil/East

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  packagesToScan: br.com.petsgft.api.pets.controller

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

dogapi:
  user: root
  password: root
  baseurl: http://dogsgft:8081

catapi:
  user: root
  password: root
  baseurl: http://catsgft:8089