networks:
  microservices_network:  # 🔹 Criando a rede que será compartilhada
    driver: bridge

volumes:
  db_data:
  rabbit_data:
  mailhog_data:

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - microservices_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices_network  # 🔹 Adicionado à rede

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_pets
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
   # command: --default-authentication-plugin=mysql_native_password
    command: --default-authentication-plugin=mysql_native_password --default-time-zone='-03:00' --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - microservices_network  # 🔹 Adicionado à rede
